comet:
  _target_: pytorch_lightning.loggers.comet.CometLogger
  # api_key: ${oc.env:COMET_API_TOKEN}                        # api key is loaded from environment variable
  project_name: ???                                           # name of the project
  workspace: ???                                              # workspace name, set with '<name>'
  save_dir: logs/lighting                                     # Logging directory for comet

# Comet tag
tag: ???
